"""Constants for Home Assistant Energy Optimizer.

Only implementation defaults live here. Installation-specific entity IDs,
addresses and battery settings are stored in the Home Assistant config entry.
"""

from datetime import timedelta

DOMAIN = "energy_optimizer"
NAME = "Home Assistant Energy Optimizer"
UPDATE_INTERVAL = timedelta(minutes=5)

CONF_PRICE_TIMELINE_ENTITY = "price_timeline_entity"
CONF_PRICE_HISTORY_ENTITY = "price_history_entity"
CONF_SOC_ENTITY = "soc_entity"
CONF_PV_TODAY_REMAINING_ENTITY = "pv_today_remaining_entity"
CONF_PV_TOMORROW_ENTITY = "pv_tomorrow_entity"
CONF_LIVE_PV_POWER_ENTITY = "live_pv_power_entity"
CONF_LIVE_GRID_POWER_ENTITY = "live_grid_power_entity"
CONF_LIVE_LOAD_POWER_ENTITIES = "live_load_power_entities"
CONF_GRID_IMPORT_ENERGY_ENTITY = "grid_import_energy_entity"
CONF_GRID_EXPORT_ENERGY_ENTITY = "grid_export_energy_entity"
CONF_PV_ENERGY_ENTITY = "pv_energy_entity"
CONF_BATTERY_CHARGE_ENERGY_ENTITY = "battery_charge_energy_entity"
CONF_BATTERY_DISCHARGE_ENERGY_ENTITY = "battery_discharge_energy_entity"
CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_HARD_MIN_SOC = "hard_min_soc"
CONF_EXPORT_EUR_KWH = "export_eur_kwh"
CONF_BATTERY_WEAR_EUR_KWH = "battery_wear_eur_kwh"
CONF_GRID_CHARGE_MARGIN_EUR_KWH = "grid_charge_margin_eur_kwh"
CONF_ALLOW_GRID_CHARGING = "allow_grid_charging"
CONF_QUIET_HOURS_START = "quiet_hours_start"
CONF_QUIET_HOURS_END = "quiet_hours_end"
CONF_QUIET_GRID_CHARGE_KW = "quiet_grid_charge_kw"
CONF_DAY_GRID_CHARGE_KW = "day_grid_charge_kw"
CONF_QUIET_CHARGE_CURRENT_A = "quiet_charge_current_a"
CONF_NORMAL_CHARGE_CURRENT_A = "normal_charge_current_a"
CONF_CONTROL_ENABLE_ENTITY = "control_enable_entity"
CONF_WEATHER_TEMPERATURE_ENTITY = "weather_temperature_entity"
CONF_WEATHER_CLOUD_ENTITY = "weather_cloud_entity"
CONF_WEATHER_ILLUMINANCE_ENTITY = "weather_illuminance_entity"
CONF_WEATHER_RAIN_BINARY_ENTITY = "weather_rain_binary_entity"
CONF_WEATHER_FORECAST_ENTITY = "weather_forecast_entity"
CONF_VICTRON_MODBUS_HOST = "victron_modbus_host"
CONF_VICTRON_MODBUS_PORT = "victron_modbus_port"
CONF_VICTRON_SETTINGS_UNIT_ID = "victron_settings_unit_id"
CONF_VICTRON_MAX_CHARGE_CURRENT_REGISTER = "victron_max_charge_current_register"
CONF_VICTRON_GRID_SETPOINT_REGISTER = "victron_grid_setpoint_register"
CONF_VICTRON_GRID_SETPOINT_MAX_W = "victron_grid_setpoint_max_w"

# Optional, vendor-neutral EV planning.  These remain flat config-entry keys so
# existing entries can opt in without a migration of their established data.
CONF_EV_ENABLED = "ev_enabled"
CONF_SITE_METER_INCLUDES_EV = "site_meter_includes_ev"
CONF_EV_LIVE_POWER_ENTITY = "ev_live_power_entity"
CONF_EV_ENERGY_ENTITY = "ev_energy_entity"
CONF_EV_CONNECTED_ENTITY = "ev_connected_entity"
CONF_EV_VEHICLE_SOC_ENTITY = "ev_vehicle_soc_entity"
CONF_EV_CALENDAR_ENTITY = "ev_calendar_entity"
CONF_EV_NORMAL_CHARGE_POWER_KW = "ev_normal_charge_power_kw"
CONF_EV_BOOST_CHARGE_POWER_KW = "ev_boost_charge_power_kw"
CONF_EV_BATTERY_CAPACITY_KWH = "ev_battery_capacity_kwh"
CONF_EV_CONSUMPTION_KWH_PER_100KM = "ev_consumption_kwh_per_100km"
CONF_EV_RESERVE_KM = "ev_reserve_km"
CONF_EV_CHARGE_EFFICIENCY = "ev_charge_efficiency"
CONF_SITE_MAX_IMPORT_POWER_KW = "site_max_import_power_kw"

DEFAULT_BATTERY_CAPACITY_KWH = 5.0
DEFAULT_HARD_MIN_SOC = 12.0
DEFAULT_MAX_CONTROL_SOC = 95.0
DEFAULT_BATTERY_WEAR_EUR_KWH = 0.0
DEFAULT_EXPORT_EUR_KWH = 0.0
DEFAULT_PV_CURTAILMENT_PENALTY_EUR_KWH = 0.001
DEFAULT_GRID_CHARGE_MARGIN_EUR_KWH = 0.03
DEFAULT_QUIET_HOURS_START = 21
DEFAULT_QUIET_HOURS_END = 6
DEFAULT_QUIET_GRID_CHARGE_KW = 1.6
DEFAULT_DAY_GRID_CHARGE_KW = 2.5
DEFAULT_QUIET_CHARGE_CURRENT_A = 30
DEFAULT_NORMAL_CHARGE_CURRENT_A = 50
DEFAULT_VICTRON_RELEASE_HEADROOM_PERCENT = 4.0
DEFAULT_CONTROL_COMMAND_VALID_MINUTES = 7
DEFAULT_VICTRON_MODBUS_PORT = 502
DEFAULT_VICTRON_SETTINGS_UNIT_ID = 100
DEFAULT_VICTRON_MAX_CHARGE_CURRENT_REGISTER = 2705
DEFAULT_VICTRON_GRID_SETPOINT_REGISTER = 2716
DEFAULT_VICTRON_GRID_SETPOINT_MAX_W = 3000

DEFAULT_EV_ENABLED = False
DEFAULT_SITE_METER_INCLUDES_EV = False
DEFAULT_EV_NORMAL_CHARGE_POWER_KW = 3.6
MAX_EV_AUTOMATIC_CHARGE_POWER_KW = 11.0
DEFAULT_EV_BOOST_CHARGE_POWER_KW = MAX_EV_AUTOMATIC_CHARGE_POWER_KW
DEFAULT_EV_BATTERY_CAPACITY_KWH = 60.0
DEFAULT_EV_CONSUMPTION_KWH_PER_100KM = 18.0
DEFAULT_EV_RESERVE_KM = 50.0
DEFAULT_EV_CHARGE_EFFICIENCY = 0.90
DEFAULT_SITE_MAX_IMPORT_POWER_KW = 22.0
MAX_SITE_IMPORT_POWER_KW = 60.0

# Backwards-compatible names used by the pure, deterministic control helpers.
BATTERY_CAPACITY_KWH = DEFAULT_BATTERY_CAPACITY_KWH
HARD_MIN_SOC = DEFAULT_HARD_MIN_SOC
MAX_CONTROL_SOC = DEFAULT_MAX_CONTROL_SOC
BATTERY_WEAR_EUR_KWH = DEFAULT_BATTERY_WEAR_EUR_KWH
EXPORT_EUR_KWH = DEFAULT_EXPORT_EUR_KWH
PV_CURTAILMENT_PENALTY_EUR_KWH = DEFAULT_PV_CURTAILMENT_PENALTY_EUR_KWH
GRID_CHARGE_MARGIN_EUR_KWH = DEFAULT_GRID_CHARGE_MARGIN_EUR_KWH
QUIET_HOURS_START = DEFAULT_QUIET_HOURS_START
QUIET_HOURS_END = DEFAULT_QUIET_HOURS_END
QUIET_GRID_CHARGE_KW = DEFAULT_QUIET_GRID_CHARGE_KW
DAY_GRID_CHARGE_KW = DEFAULT_DAY_GRID_CHARGE_KW
QUIET_CHARGE_CURRENT_A = DEFAULT_QUIET_CHARGE_CURRENT_A
NORMAL_CHARGE_CURRENT_A = DEFAULT_NORMAL_CHARGE_CURRENT_A
VICTRON_RELEASE_HEADROOM_PERCENT = DEFAULT_VICTRON_RELEASE_HEADROOM_PERCENT
CONTROL_COMMAND_VALID_MINUTES = DEFAULT_CONTROL_COMMAND_VALID_MINUTES
VICTRON_GRID_SETPOINT_MAX_W = DEFAULT_VICTRON_GRID_SETPOINT_MAX_W

LIVE_POWER_MAX_AGE_SECONDS = 600
LIVE_POWER_MAX_W = 30_000
LIVE_GRID_WARNING_W = 100
PV_STORE_GRID_HEADROOM_W = 30
LOAD_MODEL_RECENT_WEIGHT = 0.65
MAX_COMBINED_APPLIANCE_AVERAGE_POWER_KW = 2.5

# The public beta does not assume any particular plug, helper or appliance.
DEFAULT_APPLIANCES: dict[str, dict] = {}
DEFAULT_DEVICE_ENERGY_ENTITIES: dict[str, str] = {}
SHIFTABLE_DEVICE_KEYS = (
    "washing_machine",
    "dishwasher",
    "dryer",
    # Legacy keys accepted when migrating an existing German installation.
    "waschmaschine",
    "spuelmaschine",
    "trockner",
)
